# Dữ liệu tài liệu đề xuất bổ sung cho chuyên đề tổng quan (rà soát 30/9/2026).
# Mọi thông tin thư mục và nội dung được đọc trực tiếp từ tệp gốc trong 01_NotebookLM_Inputs.
# Trường "xac_minh": A = đủ tác giả, năm, tên, nguồn trên bản gốc; B = còn thiếu một chi tiết (ghi ở "ghi_chu").

DE_XUAT = [
    # ------------------------------------------------------------------ 1.1.1.1
    dict(id=74, muc="1.1.1.1", huong="Hướng 3: quyền SHTT trong hệ thống đổi mới sáng tạo và vai trò của Nhà nước",
         tac_gia="World Intellectual Property Organization (WIPO)", nam="2024",
         ten="Models of Intellectual Property Governance and Administration", nguon="WIPO, Geneva", so_trang="DOI 10.34667/tind.49741",
         loai="Báo cáo tổ chức quốc tế", xac_minh="A",
         van_de="Các mô hình tổ chức, điều hành và quản trị cơ quan SHTT quốc gia; vị trí của người đứng đầu cơ quan SHTT trong bộ máy nhà nước.",
         ket_qua="Người đứng đầu cơ quan SHTT vừa làm chính sách vừa điều hành hành chính; có hai loại nhiệm vụ: nhiệm vụ rộng về kinh tế, xã hội (kèm xây dựng chính sách, hỗ trợ kỹ thuật, nghiên cứu kinh tế) và nhiệm vụ tập trung vận hành dịch vụ SHTT; phần lớn cơ quan bị giới hạn về biên chế và ngân sách; ưu tiên chung là đào tạo, nâng cao năng lực và cải thiện chất lượng dịch vụ bằng công nghệ số, trí tuệ nhân tạo.",
         phuong_phap="Nghiên cứu so sánh dựa trên phỏng vấn người đứng đầu cơ quan SHTT", mau="25 cơ quan SHTT (Phụ lục A.2, A.5)", phan_tich="Phân tích định tính, so sánh mô hình",
         nguyen_van="Heads of IP offices interviewed say that their role involves balancing legal, administrative, strategic and diplomatic aspects while contributing to national public policy objectives and priorities of the government.",
         dung_cho_LA="Cung cấp cơ sở so sánh về tổ chức bộ máy và cơ chế phối hợp chính sách SHTT; gợi ý nội dung QLNN về tổ chức bộ máy và phối hợp liên ngành, trong đó có yếu tố nguồn lực của cơ quan quản lý mà chuyên đề nhận định là còn ít được phân tích.",
         trang="PDF tr. 9-10 (Executive summary); mục 1.3-1.4 về mô hình trách nhiệm cấp bộ và cơ chế phối hợp chính sách",
         ghi_chu="Siêu dữ liệu tệp ghi các tác giả Thumm N., Blind K., Stolz C.; trích dẫn theo đề nghị của WIPO là WIPO (2024). Bản trùng: bo sung tai lieu tong quan chat gpt/wipo-pub-2009-...pdf (thực chất là bản 2024)."),
    dict(id=466, muc="1.1.1.1", huong="Hướng 2: vai trò của quyền SHTT đối với tăng trưởng, đầu tư",
         tac_gia="Fink C., Maskus K.E., Qian Y.", nam="2016",
         ten="The economic effects of counterfeiting and piracy: A review and implications for developing countries", nguon="The World Bank Research Observer", so_trang="31, 1-28; doi:10.1093/wbro/lkv010",
         loai="Bài báo tổng quan", xac_minh="A",
         van_de="Tác động kinh tế, xã hội của hành vi làm giả nhãn hiệu và vi phạm bản quyền, nhất là ở các nước đang phát triển.",
         ket_qua="Tổng quan các nghiên cứu học thuật và công bố chính sách về tác động của vi phạm quyền SHTT theo loại quyền và ngành; chỉ ra những khoảng trống hiểu biết và đề xuất cách Chính phủ thu thập dữ liệu, tổ chức nghiên cứu để hoạch định chính sách thực thi tốt hơn.",
         phuong_phap="Tổng quan tài liệu", mau="", phan_tich="Tổng hợp, đánh giá",
         nguyen_van="We also identify important gaps in our understanding of the consequences of counterfeiting and piracy and develop recommendations on how governments might collect data and conduct studies to better inform policy.",
         dung_cho_LA="Bổ sung cho hướng 2 góc nhìn về thực thi quyền: hiệu quả thực thi phụ thuộc vào dữ liệu và bằng chứng mà cơ quan nhà nước thu thập; liên hệ với yếu tố (1) và (4) ở Bảng 1.2.",
         trang="tr. 1 (tóm tắt)",
         ghi_chu="Bản trực tuyến công bố ngày 7/5/2015; tập 31 in năm 2016. NCS đối chiếu năm theo DOI khi đưa vào danh mục."),
    dict(id=241, muc="1.1.1.1", huong="Hướng 1: bản chất và cơ sở biện minh của quyền SHTT",
         tac_gia="Drahos P.", nam="1996 (bản ANU eText 2016)",
         ten="A Philosophy of Intellectual Property", nguon="Dartmouth Publishing Company (bản in 1996); ANU eText, Canberra (2016)", so_trang="ISBN 9781925022957 (ebook)",
         loai="Sách chuyên khảo", xac_minh="A",
         van_de="Cơ sở triết học của quyền SHTT và giới hạn của cách tiếp cận coi quyền SHTT là quyền tài sản.",
         ket_qua="Tác giả đề xuất lấy chủ nghĩa công cụ (instrumentalism) làm định hướng xây dựng lý thuyết SHTT; cho rằng nên thay ngôn ngữ quyền tài sản bằng ngôn ngữ đặc quyền, trong đó các nghĩa vụ gắn với đặc quyền là cốt lõi của lý thuyết SHTT.",
         phuong_phap="Phân tích triết học, pháp lý", mau="", phan_tich="Phân tích lý luận",
         nguyen_van="instrumentalism should be our guide in constructing interdisciplinary approaches and theories of intellectual property. Amongst other things, this means that in the case of intellectual property the language of privilege should replace the existing language of property rights.",
         dung_cho_LA="Củng cố luận điểm của hướng 1 rằng quyền SHTT là chế định do Nhà nước thiết kế và có thể điều chỉnh; đặt cạnh Hughes (1988), Fisher (2001), Merges (2011) để thể hiện luồng quan điểm phản biện.",
         trang="PDF tr. 14 (Introduction)", ghi_chu=""),
    # ------------------------------------------------------------------ 1.1.1.2
    dict(id=379, muc="1.1.1.2", huong="Hướng 2: bảo hộ và thực thi quyền đối với các đối tượng cụ thể",
         tac_gia="Trần Văn Hải", nam="2021",
         ten="Chính sách pháp luật hình sự Việt Nam đối với các tội xâm phạm quyền sở hữu trí tuệ", nguon="Luận án tiến sĩ Luật học, Học viện Khoa học xã hội", so_trang="175 tr.",
         loai="Luận án tiến sĩ", xac_minh="A",
         van_de="Lý luận và thực trạng chính sách pháp luật hình sự đối với các tội xâm phạm quyền SHTT.",
         ket_qua="Xây dựng khái niệm, đặc điểm, mục tiêu, nội dung và các yếu tố tác động của chính sách pháp luật hình sự đối với nhóm tội này; đánh giá thực trạng thể hiện trong pháp luật hình sự qua các thời kỳ và thực trạng phát hiện, xử lý qua bản án, số liệu thống kê; đề xuất giải pháp hoàn thiện.",
         phuong_phap="Phân tích pháp luật, nghiên cứu bản án, thống kê", mau="Bản án hình sự và số liệu thống kê", phan_tich="Định tính, thống kê mô tả",
         nguyen_van="", dung_cho_LA="Bổ sung cơ chế thực thi bằng biện pháp hình sự cho hướng 2; làm rõ yếu tố hiệu lực thực thi quyền, một điều kiện của khai thác.",
         trang="Trích yếu luận án, tr. 1-2", ghi_chu="Không trùng với Tran Van Hai (2022) đã trích dẫn (tác giả khác, VNU Journal)."),
    dict(id=404, muc="1.1.1.2", huong="Hướng 2: bảo hộ và thực thi quyền đối với các đối tượng cụ thể",
         tac_gia="Hứa Thị Hồng", nam="2023",
         ten="Bảo vệ quyền sở hữu trí tuệ tại biên giới thông qua kiểm soát hàng hoá giả mạo về sở hữu trí tuệ của Hải quan Việt Nam", nguon="Luận án tiến sĩ Luật học, Trường Đại học Luật Hà Nội", so_trang="325 tr.",
         loai="Luận án tiến sĩ", xac_minh="A",
         van_de="Cơ sở lý luận, pháp luật và thực tiễn kiểm soát hàng hoá giả mạo về SHTT tại biên giới.",
         ket_qua="Làm rõ nội hàm hàng hoá giả mạo về SHTT và tiêu chí xác định; xây dựng mô hình lý thuyết về kiểm soát hàng hoá giả mạo của Hải quan; phân tích vướng mắc của pháp luật và đề xuất hoàn thiện.",
         phuong_phap="Phân tích pháp luật, so sánh", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Bổ sung chủ thể thực thi là cơ quan hải quan, cho thấy tính liên ngành của QLNN về quyền SHTT; liên hệ với nội dung phối hợp liên ngành.",
         trang="Thông tin những đóng góp mới, tr. 1", ghi_chu=""),
    dict(id=394, muc="1.1.1.2", huong="Hướng 1: nền tảng lý luận pháp lý",
         tac_gia="Phạm Minh Huyền", nam="2024",
         ten="Giới hạn quyền tác giả, quyền liên quan - Những vấn đề lý luận và thực tiễn", nguon="Luận án tiến sĩ Luật học, Trường Đại học Luật Hà Nội", so_trang="238 tr.",
         loai="Luận án tiến sĩ", xac_minh="A",
         van_de="Lý luận về giới hạn quyền tác giả, quyền liên quan và yêu cầu mới từ môi trường số.",
         ket_qua="Xây dựng khái niệm khoa học và bốn đặc điểm của giới hạn quyền tác giả, quyền liên quan; phân tích cơ sở lý luận từ quan điểm của Locke, Hegel, học thuyết cân bằng lợi ích, học thuyết hết quyền, học thuyết sử dụng hợp lý; phân tích quy định trong các điều ước quốc tế mà Việt Nam là thành viên.",
         phuong_phap="Phân tích, so sánh pháp luật", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Làm dày hướng 1 (hiện chỉ có Lê Nết, 2006); cho thấy nghiên cứu trong nước bắt đầu tiếp cận cơ sở biện minh của quyền, tương ứng với hướng 1 của mục 1.1.1.1.",
         trang="Thông tin những điểm mới, tr. 1", ghi_chu=""),
    dict(id=276, muc="1.1.1.2", huong="Hướng 2: bảo hộ và thực thi quyền, kể cả trong môi trường số",
         tac_gia="Nguyễn Hồ Bích Hằng", nam="2025",
         ten="[Tên tiếng Việt cần đối chiếu bản in] (tên tiếng Anh: Legislation on intellectual property in cross-border commercial transactions in the context of digital transformation)", nguon="Tạp chí Luật học", so_trang="số 1/2025, tr. 78-91",
         loai="Bài báo khoa học", xac_minh="B",
         van_de="Bảo vệ quyền SHTT trong giao dịch thương mại xuyên biên giới trong bối cảnh chuyển đổi số.",
         ket_qua="Việc thực thi, bảo vệ quyền SHTT tại Việt Nam còn nhiều thách thức; blockchain, hợp đồng thông minh, trí tuệ nhân tạo có thể hỗ trợ bảo vệ quyền nhưng cần khắc phục khoảng cách pháp lý và công nghệ; đề xuất giải pháp cho giao dịch xuyên biên giới.",
         phuong_phap="Phân tích pháp luật", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Bổ sung công trình mới nhất về thực thi quyền trong môi trường số cho hướng 2.",
         trang="tr. 78 (tóm tắt)", ghi_chu="Tên bài tiếng Việt không đọc được trên bản PDF (dạng ảnh); số trang cuối suy từ 14 trang của tệp, cần đối chiếu."),
    # ------------------------------------------------------------------ 1.1.2.1
    dict(id=545, muc="1.1.2.1", huong="Hướng 1: khái niệm và đo lường kinh tế số",
         tac_gia="OECD", nam="2014", ten="Measuring the Digital Economy: A New Perspective", nguon="OECD Publishing, Paris", so_trang="doi:10.1787/9789264221796-en",
         loai="Báo cáo tổ chức quốc tế", xac_minh="A",
         van_de="Đối chiếu hệ thống chỉ báo hiện có với các vấn đề chính sách kinh tế số, xác định khoảng trống đo lường.",
         ket_qua="Rà soát các chỉ báo hiện có, chỉ ra khoảng trống của khung đo lường và đề xuất chương trình đo lường quốc tế cho kinh tế số.",
         phuong_phap="Tổng hợp thống kê, rà soát chỉ báo", mau="Các nước OECD", phan_tich="Thống kê mô tả",
         nguyen_van="Measuring the Digital Economy maps existing indicators against digital economy policy issues, identifies gaps in the measurement framework, assesses progress, and proposes a forward-looking international measurement agenda.",
         dung_cho_LA="Là mắt xích giữa Bukht và Heeks (2017) và OECD (2020) trong quá trình phát triển phương pháp đo lường; cho thấy đo lường kinh tế số được đặt ra như một yêu cầu chính sách.",
         trang="PDF tr. 15 (Executive summary, tr. in 13)", ghi_chu=""),
    dict(id=537, muc="1.1.2.1", huong="Hướng 1: khái niệm và đo lường kinh tế số",
         tac_gia="Barefoot K., Curtis D., Jolliff W., Nicholson J.R., Omohundro R.", nam="2018",
         ten="Defining and Measuring the Digital Economy", nguon="Working Paper, Bureau of Economic Analysis, U.S. Department of Commerce", so_trang="ngày 15/3/2018",
         loai="Tài liệu làm việc", xac_minh="A",
         van_de="Xây dựng ước tính cho tài khoản vệ tinh kinh tế số trong hệ thống tài khoản quốc gia Hoa Kỳ.",
         ket_qua="Đề xuất quy trình ba bước: định nghĩa khái niệm kinh tế số, xác định nhóm hàng hóa và dịch vụ tương ứng trong khung cung - sử dụng, và ước tính đóng góp của kinh tế số vào GDP.",
         phuong_phap="Hạch toán quốc gia", mau="Dữ liệu cung - sử dụng của Hoa Kỳ", phan_tich="Ước tính thống kê",
         nguyen_van="These estimates are the first step to a comprehensive measure of the contribution of the digital economy to gross domestic product (GDP).",
         dung_cho_LA="Cung cấp phương pháp đo lường theo tài khoản quốc gia, làm căn cứ so sánh với chỉ tiêu tỷ trọng kinh tế số trong GDP do Cục Thống kê công bố năm 2026.",
         trang="PDF tr. 3 (Abstract)", ghi_chu=""),
    dict(id=520, muc="1.1.2.1", huong="Hướng 1 và 2: khái niệm; cơ chế kinh tế của công nghệ số",
         tac_gia="UNCTAD", nam="2017", ten="The 'New' Digital Economy and Development", nguon="UNCTAD Technical Notes on ICT for Development No. 8, Geneva", so_trang="TN/UNCTAD/ICT4D/08",
         loai="Báo cáo kỹ thuật", xac_minh="A",
         van_de="Nhận diện các thành phần và đặc điểm mới của kinh tế số đối với các nước đang phát triển.",
         ket_qua="Kinh tế số mới gồm sản xuất tiên tiến, robot, dữ liệu từ kết nối di động, điện toán đám mây, phân tích dữ liệu lớn và trí tuệ nhân tạo; ba đặc điểm mới là nguồn dữ liệu mới, mô hình kinh doanh nền tảng và tự động hóa.",
         phuong_phap="Phân tích tổng hợp", mau="", phan_tich="Định tính",
         nguyen_van="Second, new business models based on technology and product platforms",
         dung_cho_LA="Nối hướng 1 với hướng 3: mô hình nền tảng là cơ chế dẫn đến tập trung giá trị mà UNCTAD (2019) và Foster (2024) phân tích.",
         trang="PDF tr. 2 (Abstract)", ghi_chu=""),
    dict(id=546, muc="1.1.2.1", huong="Hướng 3: phân phối giá trị và vai trò chính sách ở nước đang phát triển",
         tac_gia="Dahlman C., Mealy S., Wermelinger M.", nam="2016",
         ten="Harnessing the digital economy for developing countries", nguon="OECD Development Centre Working Papers No. 334, OECD Publishing, Paris", so_trang="doi:10.1787/4adffb24-en",
         loai="Tài liệu làm việc", xac_minh="A",
         van_de="Vì sao kinh tế số quan trọng với nước đang phát triển và các yếu tố cần tính đến khi xây dựng chiến lược số quốc gia.",
         ket_qua="Lợi ích của kinh tế số không tự đến mà đòi hỏi Chính phủ hoạch định chiến lược để tối đa hóa tác động phát triển và phân phối lợi ích đồng đều; đề xuất các yếu tố nền tảng rút từ kinh nghiệm các nền kinh tế dẫn đầu.",
         phuong_phap="Phân tích tổng hợp, nghiên cứu tình huống quốc gia", mau="", phan_tich="Định tính",
         nguyen_van="However, this does not just happen randomly: governments must engage in strategic planning to maximise the development impact of digitalisation and ensure that its benefits are evenly distributed.",
         dung_cho_LA="Bổ sung luận điểm về vai trò chủ động của Nhà nước ở nước đang phát triển cho hướng 3, qua đó nối sang hạn chế đã nêu của mục 1.1.2.1.",
         trang="PDF tr. 7 (Abstract)", ghi_chu=""),
    dict(id=499, muc="1.1.2.1", huong="Hướng 2: tài sản vô hình",
         tac_gia="WIPO, Luiss Business School", nam="2024", ten="World Intangible Investment Highlights", nguon="WIPO, Geneva", so_trang="",
         loai="Báo cáo thống kê", xac_minh="A",
         van_de="Đo lường đầu tư vào tài sản vô hình ở các nền kinh tế.",
         ket_qua="Đầu tư vào tài sản vô hình (R&D, phần mềm và dữ liệu, thương hiệu, thiết kế) tăng nhanh gấp ba lần đầu tư vào tài sản hữu hình trong giai đoạn 2008-2023 và chiếm tỷ trọng ngày càng lớn trong GDP.",
         phuong_phap="Thống kê (Global INTAN-Invest Database)", mau="Các nền kinh tế thu nhập cao và mới nổi", phan_tich="Thống kê mô tả",
         nguyen_van="intangible investments grew at three times the rate of tangible investments between 2008-2023",
         dung_cho_LA="Cập nhật số liệu gần đây cho luận điểm của Haskel và Westlake (2018) về vai trò trung tâm của tài sản vô hình.",
         trang="tr. 1 (Key trends and insights)", ghi_chu="Có bản 2025 (lần thứ hai) trong thư mục 16_Lyluan_SHTT."),
    dict(id=264, muc="1.1.2.1", huong="Đề xuất hướng 4: quan hệ giữa bảo hộ quyền SHTT và phát triển kinh tế số",
         tac_gia="Chen W., Wu Y.", nam="2022",
         ten="Does intellectual property protection stimulate digital economy development?", nguon="Journal of Applied Economics", so_trang="25(1), 723-730; doi:10.1080/15140326.2022.2045846",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Tác động của bảo hộ quyền SHTT đến phát triển kinh tế số cấp tỉnh ở Trung Quốc.",
         ket_qua="Quan hệ giữa bảo hộ quyền SHTT và kinh tế số có dạng chữ U; kết quả vững sau các kiểm định.",
         phuong_phap="Định lượng, chỉ số kinh tế số tự xây dựng", mau="Các tỉnh của Trung Quốc", phan_tich="Hồi quy, kiểm định độ vững",
         nguyen_van="We find that there is a U-shaped relationship between intellectual property protection and digital economy.",
         dung_cho_LA="Bằng chứng cho luận điểm tác động có điều kiện của quyền SHTT (mục 1.1.1.1) khi đặt trong kinh tế số; tạo đối xứng với hướng 3 của mục 1.1.2.2.",
         trang="tr. 723 (Abstract)", ghi_chu="Bản trùng có ở 05_BaiBao_QuocTe, 07_KinhNghiem_TrungQuoc, 14_SHTT_KTS, 16_Lyluan_SHTT."),
    dict(id=76, muc="1.1.2.1", huong="Đề xuất hướng 4: quan hệ giữa bảo hộ quyền SHTT và phát triển kinh tế số",
         tac_gia="Zheng P., Li Z., Zhuang Z.", nam="2023",
         ten="The impact of judicial protection of intellectual property on digital innovation: Evidence from China", nguon="Finance Research Letters", so_trang="58, 104257; doi:10.1016/j.frl.2023.104257",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Tác động của việc thành lập tòa án SHTT đến đổi mới sáng tạo số của doanh nghiệp.",
         ket_qua="Tăng cường bảo hộ tư pháp đối với quyền SHTT tác động tích cực đến đổi mới sáng tạo số, rõ hơn ở công nghệ số nền tảng và ở doanh nghiệp nhỏ.",
         phuong_phap="Định lượng, sai phân ba lần (DDD)", mau="Doanh nghiệp niêm yết hạng A của Trung Quốc, 2009-2020", phan_tich="DDD",
         nguyen_van="small firms are more likely to be affected by judicial protection of IP in their digital innovation activities than large firms.",
         dung_cho_LA="Gợi ý rằng hiệu lực thực thi quyền, một yếu tố thuộc bộ máy nhà nước, có ý nghĩa với doanh nghiệp nhỏ trong môi trường số.",
         trang="tr. 1 (Abstract)", ghi_chu=""),
    dict(id=103, muc="1.1.2.1", huong="Đề xuất hướng 4: quan hệ giữa bảo hộ quyền SHTT và phát triển kinh tế số",
         tac_gia="Yuan B., Li W.", nam="2025",
         ten="Legal infrastructures for firm innovation: Effects of intellectual property protection in the era of digital economy", nguon="Finance Research Letters", so_trang="71, 106343; doi:10.1016/j.frl.2024.106343",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Tác động của bảo hộ quyền SHTT đến đổi mới sáng tạo của doanh nghiệp và vai trò trung gian của chuyển đổi số.",
         ket_qua="Bảo hộ quyền SHTT tác động tích cực đến đổi mới sáng tạo; chuyển đổi số là biến trung gian khuếch đại tác động; tác động yếu hơn ở ngành công nghệ cao.",
         phuong_phap="Định lượng", mau="Doanh nghiệp niêm yết hạng A của Trung Quốc, 2018-2022", phan_tich="Hồi quy, phân tích trung gian",
         nguyen_van="the positive effect of intellectual property protection on firm innovation is found to be weaker high-tech industries than that in non-high-tech industries.",
         dung_cho_LA="Cho thấy tác động của bảo hộ khác nhau theo ngành, củng cố cách nhìn có điều kiện.",
         trang="tr. 1 (Abstract)", ghi_chu=""),
    dict(id=114, muc="1.1.2.1", huong="Đề xuất hướng 4: quan hệ giữa bảo hộ quyền SHTT và phát triển kinh tế số",
         tac_gia="Ding T., Yang L.", nam="2025",
         ten="Intellectual property protection and corporate digital transformation: An empirical analysis from the perspectives of intellectual property protection and digital governance", nguon="International Review of Economics & Finance", so_trang="100, 104125; doi:10.1016/j.iref.2025.104125",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Quan hệ giữa bảo hộ quyền SHTT, quản trị số của chính quyền và chuyển đổi số của doanh nghiệp.",
         ket_qua="Bảo hộ quyền SHTT và quản trị số đều thúc đẩy chuyển đổi số của doanh nghiệp; quản trị số tăng tính minh bạch của chính quyền và điều tiết tích cực quan hệ giữa bảo hộ quyền SHTT với chuyển đổi số, khác nhau giữa các vùng.",
         phuong_phap="Định lượng", mau="Doanh nghiệp niêm yết hạng A của Trung Quốc, 2013-2022", phan_tich="Hồi quy, biến điều tiết",
         nguyen_van="digital governance plays a positive moderating role in the relationship between intellectual property protection and corporate digital transformation",
         dung_cho_LA="Là một trong số ít công trình đưa năng lực quản trị của chính quyền vào mô hình; gắn trực tiếp với tiêu chí minh bạch và nội dung quản trị số của luận án.",
         trang="tr. 1 (Abstract)", ghi_chu="Bản trùng ở 05_BaiBao_QuocTe/Khai thác/Quan trọng."),
    # ------------------------------------------------------------------ 1.1.2.2
    dict(id=293, muc="1.1.2.2", huong="Hướng 1: khái niệm, thực trạng và đo lường kinh tế số",
         tac_gia="Trần Thị Lan", nam="2025", ten="Các yếu tố ảnh hưởng đến phát triển kinh tế số ở Việt Nam", nguon="Luận án tiến sĩ Kinh tế (Kinh tế phát triển), Học viện Khoa học xã hội", so_trang="200 tr.",
         loai="Luận án tiến sĩ", xac_minh="A",
         van_de="Xác định và đo lường các yếu tố ảnh hưởng đến phát triển kinh tế số ở Việt Nam.",
         ket_qua="Tiếp cận phát triển kinh tế số theo hai nội dung sản xuất số và thị trường số; sáu biến độc lập gồm tỷ lệ lao động qua đào tạo, mức độ phổ cập Internet, thể chế số, FDI, an toàn thông tin và trình độ phát triển kinh tế; hầu hết tác động tích cực, riêng GRDP bình quân đầu người tác động ngược chiều.",
         phuong_phap="Kết hợp định tính và định lượng", mau="Dữ liệu bảng cấp tỉnh", phan_tich="Pooled OLS, FEM, REM, FGLS",
         nguyen_van="", dung_cho_LA="Là luận án kinh tế gần nhất về kinh tế số ở Việt Nam; thể chế số được xác định là yếu tố ảnh hưởng, song quyền SHTT chưa được đưa vào mô hình, qua đó củng cố khoảng trống của mục 1.1.2.2.",
         trang="PDF tr. 174-175 (Kết luận); danh mục bảng tr. 13", ghi_chu=""),
    dict(id=3, muc="1.1.2.2", huong="Hướng 1: khái niệm, thực trạng và đo lường kinh tế số",
         tac_gia="Nguyễn Phương Thảo", nam="2024", ten="Phương pháp đo lường kinh tế số của các tổ chức trên thế giới và đề xuất cho Việt Nam", nguon="Tạp chí Kinh tế và Dự báo", so_trang="số 21/2024, tr. 27-30",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="So sánh phương pháp đo lường kinh tế số của OECD, ADB, BEA.",
         ket_qua="Hệ thống hóa phương pháp đo lường của OECD, ADB và BEA; đề xuất khuyến nghị phát triển đo lường kinh tế số tại Việt Nam.",
         phuong_phap="Tổng hợp, so sánh", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Bổ sung cho Bui Xuan Chung (2025) về đo lường; cho thấy trong nước tiếp thu nhanh các khung đo lường quốc tế.",
         trang="tr. 27 (Tóm tắt)", ghi_chu="Số trang suy từ tên tệp và trang cuối (tr. 30)."),
    dict(id=273, muc="1.1.2.2", huong="Hướng 2: thể chế và QLNN đối với kinh tế số",
         tac_gia="Nguyễn Thị Hải Hà", nam="2023", ten="Đánh giá hiệu quả quản lý nhà nước trong nền kinh tế số", nguon="Tạp chí Phát triển bền vững Vùng", so_trang="13(2), tr. 11-20",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Chưa có hệ thống tiêu chí đánh giá QLNN đối với kinh tế số; đề xuất mô hình đánh giá.",
         ket_qua="Ở Việt Nam đã có các bộ chỉ số PAR index, PCI, SIPAS, PAPI nhưng chưa có hệ thống tiêu chí đánh giá QLNN đối với kinh tế số; bài viết gợi ý mô hình đánh giá hiệu quả QLNN dựa trên mô hình lăng kính hiệu suất.",
         phuong_phap="Tổng quan, đề xuất mô hình", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Công trình trực tiếp nhất về tiêu chí đánh giá QLNN trong kinh tế số; là căn cứ cho khoảng trống 'Thứ hai' ở mục 1.2.3 và tham chiếu cho năm tiêu chí đánh giá của luận án.",
         trang="tr. 11 (Tóm tắt, Đặt vấn đề)", ghi_chu="Số trang suy từ 10 trang của tệp, bắt đầu tr. 11."),
    dict(id=303, muc="1.1.2.2", huong="Hướng 2: thể chế và QLNN đối với kinh tế số",
         tac_gia="Ngô Hoài Sơn, Nguyễn Lê Kim Kiều", nam="2022", ten="Vận dụng lý thuyết phương pháp quản lý nhà nước về kinh tế để xây dựng nền kinh tế số ở Việt Nam", nguon="Tạp chí Công Thương", so_trang="số 21 (tháng 9/2022), tr. 248-254",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Vận dụng các phương pháp QLNN về kinh tế vào xây dựng kinh tế số.",
         ket_qua="Đề xuất giải pháp theo ba nhóm phương pháp: hành chính, kinh tế và tâm lý giáo dục trong QLNN về kinh tế.",
         phuong_phap="Phân tích tài liệu thứ cấp", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Cho thấy cách tiếp cận của khoa học quản lý kinh tế đối với kinh tế số trong nước; tham chiếu khi xác định phương thức QLNN ở Chương 2.",
         trang="tr. 248 (Tóm tắt)", ghi_chu="Trang đầu suy từ 7 trang, trang cuối 254."),
    dict(id=291, muc="1.1.2.2", huong="Hướng 2: thể chế và QLNN đối với kinh tế số",
         tac_gia="Trương Nam Trung", nam="2020", ten="Institutional improvements for the development of digital economy in Vietnam", nguon="Tạp chí Công Thương", so_trang="số 25 (tháng 10/2020), tr. 99-104",
         loai="Bài báo khoa học (tiếng Anh)", xac_minh="A",
         van_de="Hoàn thiện thể chế phát triển kinh tế số ở Việt Nam.",
         ket_qua="Kinh tế số có đặc điểm khác biệt, phát triển kinh tế số là tất yếu nhưng Việt Nam chịu nhiều áp lực cạnh tranh; nêu bất cập thể chế như chênh lệch nghĩa vụ thuế giữa nhà cung cấp nước ngoài và doanh nghiệp trong nước.",
         phuong_phap="Phân tích chính sách", mau="", phan_tich="Định tính",
         nguyen_van="Google, Facebook, Grab, and so on only have to pay 5 per cent of the foreign contractor tax whereas domestic enterprises providing similar services have to pay 25 per cent of corporate income tax",
         dung_cho_LA="Minh họa cho luận điểm về phân phối giá trị bất lợi cho chủ thể trong nước (UNCTAD, 2019; Foster, 2024) từ góc độ thể chế.",
         trang="tr. 99-100; tóm tắt tiếng Việt tr. 104", ghi_chu=""),
    dict(id=295, muc="1.1.2.2", huong="Hướng 3: tác động của kinh tế số đối với hệ thống SHTT",
         tac_gia="Nguyễn Thị Tuyết Nga", nam="2025", ten="Hoàn thiện chính sách sở hữu trí tuệ trong nền kinh tế số ở Việt Nam hiện nay", nguon="Tạp chí Quản lý nhà nước (điện tử), quanlynhanuoc.vn", so_trang="đăng ngày 30/6/2025",
         loai="Bài báo tạp chí điện tử", xac_minh="A",
         van_de="Thực trạng chính sách quản lý tài sản trí tuệ trong kinh tế số và giải pháp hoàn thiện.",
         ket_qua="Tài sản trí tuệ trở thành nguồn lực chiến lược; bài viết phân tích thực trạng chính sách quản lý tài sản trí tuệ, thách thức và đề xuất nhóm giải pháp hoàn thiện.",
         phuong_phap="Phân tích chính sách", mau="", phan_tich="Định tính",
         nguyen_van="", dung_cho_LA="Bổ sung công trình tiếp cận từ chính sách quản lý tài sản trí tuệ (không chỉ bảo hộ) cho hướng 3.",
         trang="Đoạn mở đầu và mục 1", ghi_chu="Tệp .docx lưu từ trang web; nên trích theo URL bài gốc."),
    # ------------------------------------------------------------------ 1.1.3 (thuật ngữ) và 1.1.3.1
    dict(id=152, muc="1.1.3 (đoạn mở đầu) / 1.1.3.1", huong="Làm rõ thuật ngữ khai thác quyền SHTT; hướng 1 và 3",
         tac_gia="Kamiyama S., Sheehan J., Martinez C.", nam="2006", ten="Valuation and Exploitation of Intellectual Property", nguon="OECD Science, Technology and Industry Working Papers 2006/05, OECD Publishing, Paris", so_trang="doi:10.1787/307034817055",
         loai="Tài liệu làm việc", xac_minh="A",
         van_de="Các kênh khai thác quyền SHTT và vai trò của thị trường công nghệ, định giá.",
         ket_qua="Doanh nghiệp khai thác sáng chế không chỉ bằng đưa vào sản phẩm, quy trình mà còn bằng li-xăng, dùng làm công cụ đàm phán và huy động vốn; thị trường công nghệ hiệu quả và cơ chế định giá tốt mở rộng mọi kênh khai thác.",
         phuong_phap="Tổng quan bằng chứng", mau="", phan_tich="Tổng hợp",
         nguyen_van="they are exploiting their intellectual property, notably patents, not only by incorporating protected inventions into new products, processes and services, but also by licensing them to other firms or public research organisations (PROs), using them as bargaining chips in negotiations with other firms, and as a means of attracting external financing",
         dung_cho_LA="Nguồn quốc tế dùng trực tiếp thuật ngữ exploitation và liệt kê các kênh khai thác; phù hợp để viết đoạn làm rõ thuật ngữ đầu mục 1.1.3.",
         trang="PDF tr. 4 (Abstract)", ghi_chu=""),
    dict(id=146, muc="1.1.3 (đoạn mở đầu) / 1.1.3.1", huong="Làm rõ thuật ngữ và các hình thức khai thác",
         tac_gia="Liu Haibo (刘海波), Liu Liang (刘亮)", nam="2016", ten="知识产权商用与创新驱动发展 (Thương mại hóa quyền SHTT và phát triển dựa trên đổi mới sáng tạo)", nguon="Bulletin of Chinese Academy of Sciences (中国科学院院刊)", so_trang="31(9), 1026-1035; doi:10.16418/j.issn.1000-3045.2016.09.006",
         loai="Bài báo khoa học (tiếng Trung)", xac_minh="A",
         van_de="Định nghĩa, đặc điểm và hình thức thương mại hóa quyền SHTT.",
         ket_qua="Phân biệt sử dụng quyền SHTT vì mục đích quốc gia, học thuật và thương mại; chia thương mại hóa thành thực hiện nội bộ, lưu thông ra bên ngoài, tài chính SHTT và tố tụng; phân tích kinh nghiệm Hoa Kỳ, Nhật Bản, Hàn Quốc và đề xuất chính sách.",
         phuong_phap="Phân tích khái niệm, so sánh quốc tế", mau="", phan_tich="Định tính",
         nguyen_van="文章将知识产权商用划分为内部实施、外部流通、知识产权金融、法律诉讼等几种主要形式",
         dung_cho_LA="Cung cấp một cách phân loại hình thức khai thác có thể đối chiếu với ba nhóm hình thức khai thác mà luận án lựa chọn.",
         trang="tr. 1026 (摘要)", ghi_chu="Tên tiếng Việt trong ngoặc là bản dịch tham khảo, không phải tên chính thức; trang cuối suy từ 10 trang của tệp."),
    dict(id=418, muc="1.1.3.1", huong="Hướng 2: thương mại hóa kết quả nghiên cứu (vai trò chính sách)",
         tac_gia="Goldfarb B., Henrekson M.", nam="2003", ten="Bottom-up versus top-down policies towards the commercialization of university intellectual property", nguon="Research Policy", so_trang="32, 639-658",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Chính sách quốc gia nào hiệu quả nhất trong thúc đẩy thương mại hóa tri thức từ trường đại học; so sánh Thụy Điển và Hoa Kỳ.",
         ket_qua="Tỷ lệ thương mại hóa thấp ở Thụy Điển có thể một phần do chính sách theo mô hình từ trên xuống và môi trường học thuật không khuyến khích nhà khoa học tham gia; ngược lại, cạnh tranh giữa các trường ở Hoa Kỳ tạo tự do tương tác với doanh nghiệp.",
         phuong_phap="Phân tích so sánh thể chế", mau="Thụy Điển, Hoa Kỳ", phan_tich="Định tính",
         nguyen_van="we argue that it is likely to be true in part due to the top-down nature of Swedish policies aimed at commercializing these innovations",
         dung_cho_LA="Bằng chứng trực tiếp cho tranh luận 'Thứ nhất' ở mục 1.2.3 về mức độ và phương thức can thiệp của Nhà nước.",
         trang="tr. 639 (Abstract)", ghi_chu=""),
    dict(id=211, muc="1.1.3.1", huong="Hướng 2: thương mại hóa kết quả nghiên cứu (tranh luận về Bayh-Dole)",
         tac_gia="Shane S.", nam="2004", ten="Encouraging university entrepreneurship? The effect of the Bayh-Dole Act on university patenting in the United States", nguon="Journal of Business Venturing", so_trang="19, 127-151; doi:10.1016/S0883-9026(02)00114-3",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Tác động của Đạo luật Bayh-Dole đến hoạt động đăng ký sáng chế của trường đại học.",
         ket_qua="Hiệu quả của li-xăng trong từng ngành có tương quan có ý nghĩa với tỷ trọng sáng chế của trường đại học ở giai đoạn sau Bayh-Dole, cho thấy đạo luật tác động qua kênh thị trường li-xăng.",
         phuong_phap="Định lượng", mau="Tỷ trọng sáng chế của trường đại học 1969-1996, 117 ngành", phan_tich="Hồi quy",
         nguyen_van="the effectiveness of licensing in a line of business is significantly correlated with university share of patents in the post-Bayh-Dole period",
         dung_cho_LA="Đặt cạnh Mowery và cộng sự (2001) để thể hiện hai luồng đánh giá khác nhau về Bayh-Dole ngay trong phần thân mục 1.1.3.1.",
         trang="tr. 127 (Abstract)", ghi_chu=""),
    dict(id=200, muc="1.1.3.1", huong="Hướng 2: thương mại hóa kết quả nghiên cứu và tổ chức trung gian",
         tac_gia="Siegel D.S., Veugelers R., Wright M.", nam="2007", ten="Technology transfer offices and commercialization of university intellectual property: performance and policy implications", nguon="Oxford Review of Economic Policy", so_trang="23(4), 640-660; doi:10.1093/icb/grm036",
         loai="Bài báo tổng quan", xac_minh="A",
         van_de="Tổng quan về kết quả và hàm ý chính sách của văn phòng chuyển giao công nghệ ở Hoa Kỳ và châu Âu.",
         ket_qua="Trường đại học và vùng cần xây dựng, thực hiện chiến lược chuyển giao, thương mại hóa nhất quán và khả thi.",
         phuong_phap="Tổng quan tài liệu", mau="", phan_tich="Tổng hợp",
         nguyen_van="A key conclusion is that universities and regions must formulate and implement coherent and feasible technology transfer/commercialization strategies.",
         dung_cho_LA="Phát triển tiếp Siegel, Waldman và Link (2003) theo hướng hàm ý chính sách.",
         trang="tr. 640 (Abstract)", ghi_chu=""),
    dict(id=419, muc="1.1.3.1", huong="Hướng 2: thương mại hóa kết quả nghiên cứu",
         tac_gia="Thursby J.G., Kemp S.", nam="2002", ten="Growth and productive efficiency of university intellectual property licensing", nguon="Research Policy", so_trang="31, 109-124",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Năng suất và sự thay đổi năng suất của hoạt động li-xăng ở trường đại học Hoa Kỳ.",
         ket_qua="Li-xăng tăng vì những lý do khác ngoài việc tăng nguồn lực; với cùng mức đầu vào, trường đại học hiện nay có năng suất thương mại cao hơn trước.",
         phuong_phap="Định lượng", mau="Trường đại học Hoa Kỳ", phan_tich="DEA kết hợp hồi quy",
         nguyen_van="We find that licensing has increased for reasons other than increases in overall university resources.",
         dung_cho_LA="Gợi ý rằng yếu tố tổ chức và thể chế, không chỉ nguồn lực, quyết định kết quả khai thác; có thể dùng khi phân tích tiêu chí hiệu quả.",
         trang="tr. 109 (Abstract)", ghi_chu=""),
    dict(id=129, muc="1.1.3.1", huong="Hướng 2: tổ chức trung gian",
         tac_gia="Holgersson M., Aaboen L.", nam="2019", ten="A literature review of intellectual property management in technology transfer offices: From appropriation to utilization", nguon="Technology in Society", so_trang="59, 101132; doi:10.1016/j.techsoc.2019.04.008",
         loai="Tổng quan hệ thống", xac_minh="A",
         van_de="Cách văn phòng chuyển giao công nghệ quản lý quyền SHTT.",
         ket_qua="Nghiên cứu và thực tiễn thường coi mọi sáng chế có giá trị đều cần đăng ký và đo kết quả bằng số sáng chế, li-xăng, doanh nghiệp khởi nguồn (mô hình chiếm hữu); tác giả đề xuất mô hình sử dụng, trong đó văn phòng quản lý quyền để thúc đẩy việc sử dụng kết quả nghiên cứu công.",
         phuong_phap="Tổng quan tài liệu có hệ thống", mau="", phan_tich="Tổng hợp",
         nguyen_van="We call this established view the appropriation mode of TTOs and question it based on the logics of publicly funded research and modern IP management.",
         dung_cho_LA="Luận điểm chuyển từ đếm số quyền sang thúc đẩy sử dụng tương đồng với nhận định của luận án về sự lệch trọng tâm của quản lý về phía xác lập quyền.",
         trang="tr. 1 (Abstract)", ghi_chu=""),
    dict(id=221, muc="1.1.3.1", huong="Hướng 2: thương mại hóa và vai trò chính sách",
         tac_gia="United Nations Economic Commission for Europe (UNECE)", nam="2011", ten="Intellectual Property Commercialization: Policy Options and Practical Instruments", nguon="United Nations, New York and Geneva", so_trang="127 tr.",
         loai="Báo cáo tổ chức quốc tế", xac_minh="A",
         van_de="Lựa chọn chính sách và công cụ thực tiễn để thương mại hóa quyền SHTT, nhất là ở các nền kinh tế chuyển đổi.",
         ket_qua="Các nước phải duy trì, điều chỉnh và tạo lập khung thể chế, pháp lý thuận lợi cho tạo ra và thương mại hóa tri thức; nền kinh tế chuyển đổi gặp thêm thách thức hội nhập chuỗi giá trị; thương mại hóa ở trường đại học đòi hỏi quản trị SHTT chủ động.",
         phuong_phap="Phân tích chính sách, so sánh", mau="", phan_tich="Định tính",
         nguyen_van="To be competitive in the globalized economy, the UNECE Member States have to maintain, adapt and create institutional and legal frameworks conducive to the creation of knowledge and its commercialization.",
         dung_cho_LA="Nguồn của tổ chức quốc tế tiếp cận thương mại hóa quyền SHTT từ phía chính sách công, phù hợp với góc độ QLNN của luận án.",
         trang="PDF tr. 12 (Introduction), tr. 43 (mục B)", ghi_chu=""),
    dict(id=438, muc="1.1.3.1", huong="Hướng 3: tài chính hóa quyền SHTT",
         tac_gia="APEC Intellectual Property Rights Experts Group", nam="2023", ten="A Study on the Harmonization of the IP Financial System", nguon="APEC Secretariat, Singapore (APEC#223-CT-01.11)", so_trang="109 tr.",
         loai="Báo cáo tổ chức quốc tế", xac_minh="A",
         van_de="Khung pháp lý, thể chế và thách thức của tài chính SHTT ở các nền kinh tế APEC.",
         ket_qua="Chỉ ra các thách thức của tài chính SHTT: tín dụng phụ thuộc tài sản bảo đảm là bất động sản, rủi ro của sản phẩm tài chính dựa trên SHTT, nhận thức hạn chế của tổ chức tài chính về quyền SHTT, tính lãnh thổ của quyền.",
         phuong_phap="Nghiên cứu so sánh", mau="Các nền kinh tế APEC", phan_tich="Định tính",
         nguyen_van="the problem lies with the fact that the financial institutions not only use the collateral to supplement the credit risks, but they completely rely on such collateral.",
         dung_cho_LA="Bổ sung bằng chứng từ khu vực châu Á - Thái Bình Dương cho hướng 3, vốn đang dựa chủ yếu vào dữ liệu Hoa Kỳ.",
         trang="PDF tr. 84 (mục 4.1)", ghi_chu=""),
    dict(id=170, muc="1.1.3.1", huong="Hướng 4: khai thác quyền SHTT trong môi trường số",
         tac_gia="Lee T.", nam="2026", ten="Governing digital innovation ecosystems under risk and uncertainty: IP circulation, platform dependency, and policy orchestration in Korean content industries", nguon="Technology in Society", so_trang="88, 103495; doi:10.1016/j.techsoc.2026.103495",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Cách tạo giá trị, điều phối và quản trị hệ sinh thái nội dung số khi phụ thuộc nền tảng và bất định cao.",
         ket_qua="Xây dựng khung khái niệm cho hệ sinh thái đổi mới nội dung số, trong đó lưu thông quyền SHTT, sự phụ thuộc nền tảng và điều phối chính sách là các thành tố.",
         phuong_phap="Nghiên cứu khái niệm, tổng hợp lý thuyết", mau="Công nghiệp nội dung Hàn Quốc", phan_tich="Định tính",
         nguyen_van="Methodologically, it is a conceptual, theory-synthesizing contribution",
         dung_cho_LA="Đưa vai trò điều phối chính sách của Nhà nước vào phân tích khai thác quyền trong môi trường số, bổ sung cho hạn chế đã nêu của hướng 4.",
         trang="tr. 1 (Abstract)", ghi_chu=""),
    dict(id=130, muc="1.1.3.1", huong="Hướng 4: khai thác quyền SHTT trong môi trường số (định giá)",
         tac_gia="Fu X., Zhang J., Ai C., Fu X.M.", nam="2026", ten="Digitalisation of international trade in intellectual properties: An approach based on the utility theory of technology value", nguon="The World Economy", so_trang="49, 852-866; doi:10.1111/twec.70072",
         loai="Bài báo khoa học", xac_minh="A",
         van_de="Định giá công nghệ trong thương mại quốc tế về quyền SHTT.",
         ket_qua="Đề xuất khung định giá dựa trên lý thuyết hữu dụng với bốn thuộc tính: quy mô hữu dụng, chất lượng, khả năng chuyển giao và rủi ro; phương pháp sử dụng trí tuệ nhân tạo và dữ liệu lớn giúp định giá khách quan, rẻ và có thể mở rộng.",
         phuong_phap="Xây dựng khung lý thuyết và phương pháp", mau="", phan_tich="Định tính, mô hình",
         nguyen_van="This AI-powered approach enhances the objectivity, efficiency, affordability and scalability of technology valuation, enabling more transparent, data-driven IP trade globally.",
         dung_cho_LA="Gợi ý rằng công nghệ số có thể giảm rào cản định giá, một điểm nghẽn trong nước; liên hệ với yếu tố (4) thông tin, dữ liệu.",
         trang="tr. 852 (Abstract)", ghi_chu=""),
    dict(id=432, muc="1.1.3.1", huong="Hướng 4: khai thác quyền SHTT trong môi trường số (vai trò Nhà nước)",
         tac_gia="UNCTAD", nam="2024", ten="K-content goes global: How government support and copyright policy fuelled the Republic of Korea's creative economy", nguon="United Nations, Geneva", so_trang="ISBN 978-92-1-358548-1",
         loai="Báo cáo tổ chức quốc tế", xac_minh="A",
         van_de="Vai trò của hỗ trợ của Chính phủ và chính sách quyền tác giả trong phát triển công nghiệp nội dung Hàn Quốc.",
         ket_qua="Chính phủ Hàn Quốc đóng vai trò chiến lược từ đầu thập niên 1990 qua khung pháp luật, chương trình hỗ trợ tài chính và bảo hộ quyền tác giả mạnh; cách tiếp cận Nhà nước kiến tạo khác với cách tiếp cận để thị trường tự vận hành của nhiều nước.",
         phuong_phap="Nghiên cứu tình huống quốc gia", mau="Hàn Quốc", phan_tich="Định tính",
         nguyen_van="the Republic of Korea does not take this approach emphasizing instead a strong role for the developmental and entrepreneurial state.",
         dung_cho_LA="Minh chứng thực tiễn cho quan điểm Nhà nước kiến tạo (Mazzucato, 2013) trong tranh luận 'Thứ nhất' ở mục 1.2.3; cũng dùng được ở phần kinh nghiệm quốc tế.",
         trang="PDF tr. 33-34 (Conclusions and implications)", ghi_chu=""),
    # ------------------------------------------------------------------ 1.1.3.2
    dict(id=401, muc="1.1.3.2", huong="Hướng 1 và 3: thương mại hóa ở trường đại học; quản trị tài sản trí tuệ",
         tac_gia="Phạm Thị Thúy Hằng", nam="2021", ten="Quản lý hoạt động sở hữu trí tuệ ở các trường đại học khu vực miền Trung Việt Nam", nguon="Luận án tiến sĩ Khoa học giáo dục (Quản lý giáo dục), Trường Đại học Sư phạm Thành phố Hồ Chí Minh", so_trang="256 tr.",
         loai="Luận án tiến sĩ", xac_minh="A",
         van_de="Lý luận và thực trạng quản lý hoạt động SHTT ở trường đại học, trong đó có quản lý hoạt động khai thác thương mại tài sản SHTT.",
         ket_qua="Xác định bốn nội dung quản lý: quản lý hành chính SHTT các kết quả nghiên cứu, giảng dạy; quản lý xác lập và bảo vệ quyền; quản lý khai thác thương mại tài sản SHTT; quản lý điều kiện hỗ trợ; đánh giá thực trạng và thực nghiệm biện pháp quản lý.",
         phuong_phap="Khảo sát bảng hỏi, phỏng vấn, thực nghiệm", mau="712 người (128 cán bộ quản lý, 584 giảng viên, chuyên viên) tại Đại học Huế, Trường Đại học Quy Nhơn, Trường Đại học Tây Nguyên; 70 người được phỏng vấn; 44 học viên thực nghiệm", phan_tich="Cronbach's Alpha 0,850-0,901; điểm trung bình, độ lệch chuẩn, tương quan",
         nguyen_van="", dung_cho_LA="Luận án tiếp cận từ khoa học quản lý, khảo sát đồng thời cán bộ quản lý và người thực hiện với cùng bộ tiêu chí; là tham chiếu gần về thiết kế khảo sát nhiều nhóm chủ thể và thống kê mô tả, song giới hạn ở quản lý cấp trường.",
         trang="Tóm tắt luận án: mục 6 (Phạm vi), Bảng 2.1 (mẫu), Kết luận Chương 1", ghi_chu="Có thể bổ sung vào Bảng 1.4 và hướng 1 của mục 1.1.3.2."),
]

CAN_XAC_MINH = [
    dict(id=435, tep="08_Kinhnghiem_HanQuoc/CVvv556S192025001.pdf", mo_ta="Phan Quốc Nguyên, Trịnh Linh Chi (2025), bài về bồi thường thiệt hại do hành vi xâm phạm quyền SHTT tại Việt Nam theo kinh nghiệm quốc tế, Tạp chí Tòa án nhân dân, số 19 (kỳ I tháng 10/2025)", thieu="Tên bài bị lỗi nhận dạng ký tự; cần đối chiếu bản in", muc="1.1.1.2 (hướng 2)"),
    dict(id=321, tep="04_BaiBao_TrongNuoc/Các yếu tố ảnh hưởng đến hành vi cá nhân vi phạm bản quyền số ở Việt Nam.pdf", mo_ta="Các yếu tố ảnh hưởng đến hành vi cá nhân vi phạm bản quyền số ở Việt Nam, Tạp chí Phát triển Khoa học và Công nghệ, tập 20, số Q4-2017 (264 người, TPB/UTAUT, EFA, CFA, SEM)", thieu="Không đọc được tên tác giả trên bản PDF", muc="1.1.1.2 (hướng 2)"),
    dict(id=322, tep="04_BaiBao_TrongNuoc/320534-92b07258e7f2b129b90e6d4f4a336168.pdf", mo_ta="Nguyễn Việt Long, Đoàn Thị Ánh Ngọc, Phạm Nguyễn Thái Hà, Một số nghiên cứu thời kỳ đầu hình thành kinh tế số, số 05/2021", thieu="Không đọc được tên tạp chí", muc="1.1.2.2 (hướng 1)"),
    dict(id=8, tep="06_TaiLieu_BaiBao_DeTai/130033_e1bd4f8549846bb9.pdf", mo_ta="Trần Thị Nguyệt, Hoàn thiện khung pháp lý về hỗ trợ khởi nghiệp sáng tạo tại Việt Nam trong kỷ nguyên kinh tế số", thieu="Không có tên tạp chí, số, năm", muc="1.1.2.2 (hướng 2)"),
    dict(id=302, tep="04_BaiBao_TrongNuoc/137300_ef1af37be55fa73e.pdf", mo_ta="Bài về quan hệ sở hữu trong nền kinh tế số (dữ liệu, tài sản số), Tạp chí Khoa học chính trị, số 02/2026", thieu="Không có tên tác giả và tên bài trên các trang trích được", muc="1.1.2.2 (hướng 3)"),
    dict(id=329, tep="04_BaiBao_TrongNuoc/277303-8b5de62386b54c00118e1d23a15ed493.pdf", mo_ta="Trần Thị Hằng, Nguyễn Thị Minh Hiền, bài về quản lý nhà nước trong nền kinh tế số, Tạp chí Lý luận chính trị, số 6/2019", thieu="Tên bài bị lỗi phông chữ ở phần đầu; cần đối chiếu", muc="1.1.2.2 (hướng 2)"),
    dict(id=132, tep="05_BaiBao_QuocTe/Khai thác/19661.pdf", mo_ta="Schovsbo J. (ed.), The Exploitation of Intellectual Property Rights: In Search of the Right Balance, ATRIP Intellectual Property series", thieu="Tệp chỉ có 1 trang giới thiệu sách, không có năm và nội dung", muc="1.1.3 (thuật ngữ)"),
    dict(id=351, tep="04_BaiBao_TrongNuoc/thương mại hóa/44308-469-139881-1-10-20191216.pdf", mo_ta="SHTT - công cụ quan trọng thúc đẩy đổi mới sáng tạo, phát triển kinh tế - xã hội, Diễn đàn Khoa học và Công nghệ, số 10/2019", thieu="Không có tên tác giả", muc="1.1.1.2 (hướng 3)"),
]
