# Danh mục tài liệu tham khảo của chuyên đề tổng quan (đã kiểm chứng).
# Mỗi mục: key -> (ngôn ngữ 'vi'/'en', khóa sắp xếp, nội dung theo quy định trình bày của cơ sở đào tạo)
# Quy định: sách/luận án/báo cáo in nghiêng; bài báo đặt trong ngoặc kép, tên tạp chí in nghiêng.
# Tác giả Việt Nam xếp theo tên (không đảo họ); tác giả nước ngoài xếp theo họ; cơ quan xếp theo chữ đầu tên cơ quan.

REFS = {
    # ============================ TIẾNG VIỆT ============================
    "bct2024": ("vi", "Bộ Chính trị 2024",
        "Bộ Chính trị (2024), *Nghị quyết số 57-NQ/TW ngày 22/12/2024 về đột phá phát triển khoa học, công nghệ, đổi mới sáng tạo và chuyển đổi số quốc gia*, Hà Nội."),
    "bct2026": ("vi", "Bộ Chính trị 2026",
        "Bộ Chính trị (2026), *Kết luận số 51-KL/TW ngày 17/6/2026 về đẩy mạnh công tác sở hữu trí tuệ phục vụ phát triển kinh tế - xã hội trong tình hình mới*, Hà Nội."),
    "cameron2019": ("vi", "Cameron 2019",
        "Cameron A., Pham T.H., Atherton J. và cs (2019), *Tương lai nền kinh tế số Việt Nam: Hướng tới năm 2030 và 2045*, Cơ quan Nghiên cứu Khoa học và Công nghiệp Khối thịnh vượng chung Úc (CSIRO), Brisbane."),
    "nguyenHuuCan2017": ("vi", "Cẩn Nguyễn Hữu 2017",
        "Nguyễn Hữu Cẩn (2017), “Thực trạng phát triển tài sản trí tuệ của doanh nghiệp Việt Nam và một số gợi ý chiến lược”, *Tạp chí Khoa học và Công nghệ Việt Nam*, (12), 64-67."),
    "nguyenHuuCan2020": ("vi", "Cẩn Nguyễn Hữu 2020",
        "Nguyễn Hữu Cẩn (2020), *Quản trị tài sản trí tuệ của doanh nghiệp*, Viện Khoa học sở hữu trí tuệ, Hà Nội."),
    "cucSHTT2025": ("vi", "Cục Sở hữu trí tuệ 2025",
        "Cục Sở hữu trí tuệ (2025), *Báo cáo thường niên hoạt động sở hữu trí tuệ 2024*, Hà Nội."),
    "cucTK2026": ("vi", "Cục Thống kê 2026",
        "Cục Thống kê (2026), *Thông cáo báo chí về tỷ trọng giá trị tăng thêm của kinh tế số trong GDP, GRDP giai đoạn 2021-2025*, ngày 05/01/2026, Hà Nội."),
    "nguyenVanDong2025": ("vi", "Đông Nguyễn Văn 2025",
        "Nguyễn Văn Đông (2025), *Quyền sở hữu trí tuệ trong phát triển sản phẩm mang tên địa danh của tỉnh Bắc Ninh*, Luận án tiến sĩ Kinh tế, Trường Đại học Kinh tế và Quản trị kinh doanh, Đại học Thái Nguyên, Thái Nguyên."),
    "vuPhuongGiang2025": ("vi", "Giang Vũ Thị Phương 2025",
        "Vũ Thị Phương Giang (2025), *Bảo vệ quyền sở hữu trí tuệ đối với nhãn hiệu theo pháp luật Việt Nam hiện nay*, Luận án tiến sĩ Luật kinh tế, Học viện Khoa học xã hội, Hà Nội."),
    "nguyenChiHai2021": ("vi", "Hải Nguyễn Chí 2021",
        "Nguyễn Chí Hải, Huỳnh Thị Ly Na (2021), “Đổi mới sáng tạo trong bối cảnh phát triển nền kinh tế số ở Việt Nam”, *Tạp chí Ngân hàng*, (6)."),
    "lamXuanHung2025": ("vi", "Hùng Lâm Xuân 2025",
        "Lâm Xuân Hùng (2025), “Pháp luật về sở hữu trí tuệ trong kỷ nguyên mới”, *Tạp chí Việt Nam Hội nhập*, (371), 23-29."),
    "nguyenVinhHung2020": ("vi", "Hưng Nguyễn Vĩnh 2020",
        "Nguyễn Vĩnh Hưng, Phan Quốc Nguyên (2020), “Sự tác động của nền kinh tế số đến hệ thống pháp luật sở hữu trí tuệ tại Việt Nam”, *Tạp chí Nghề Luật*, (10)."),
    "tranThanhHuyen2021": ("vi", "Huyền Trần Thị Thanh 2021",
        "Trần Thị Thanh Huyền (2021), *Quyền sở hữu công nghiệp đối với nhãn hiệu trong thương mại điện tử*, Luận án tiến sĩ Luật học, Trường Đại học Luật Hà Nội, Hà Nội."),
    "nguyenVanKim2015": ("vi", "Kim Nguyễn Văn 2015",
        "Nguyễn Văn Kim, Nguyễn Thị Ngọc Anh (2015), “Tác động của sáng chế đối với hoạt động nghiên cứu khoa học và phát triển tiềm lực khoa học và công nghệ”, *Tạp chí Khoa học Đại học Quốc gia Hà Nội: Nghiên cứu Chính sách và Quản lý*, 31(2), 14-23."),
    "tranMyLinh2025": ("vi", "Linh Trần Nguyễn Mỹ 2025",
        "Trần Nguyễn Mỹ Linh, Nguyễn Thị Hồ Điệp, Vũ Kiều Oanh (2025), “Phát triển kinh tế số tại Việt Nam: Thực trạng và giải pháp”, *Tạp chí Thông tin Khoa học xã hội*, (9)."),
    "phamTrungLuan2025": ("vi", "Luân Phạm Trung 2025",
        "Phạm Trung Luân (2025), “Chuyển giao công nghệ đảm bảo tài sản trí tuệ cho doanh nghiệp sáng tạo”, *Tạp chí Việt Nam Hội nhập*, (371), 82-87."),
    "doanDucLuong2009": ("vi", "Lương Đoàn Đức 2009",
        "Đoàn Đức Lương (2009), “Vai trò của sở hữu trí tuệ trong nghiên cứu khoa học và chuyển giao công nghệ trong các trường đại học”, *Tạp chí Khoa học Đại học Huế*, (51), 97-103."),
    "doanDucLuong2022": ("vi", "Lương Đoàn Đức 2022",
        "Đoàn Đức Lương, Ngô Minh Tiến (2022), “Khai thác tài sản trí tuệ mang yếu tố địa danh ở tỉnh Quảng Ngãi: Thực trạng và một số tồn tại hạn chế”, *Tạp chí Pháp luật và Thực tiễn*, (51), 79-88."),
    "leNet2006": ("vi", "Nết Lê 2006",
        "Lê Nết (2006), *Quyền sở hữu trí tuệ*, Nhà xuất bản Đại học Quốc gia Thành phố Hồ Chí Minh, Thành phố Hồ Chí Minh."),
    "hoThuyNgoc2025": ("vi", "Ngọc Hồ Thúy 2025",
        "Hồ Thúy Ngọc (2025), *Bảo hộ quyền sở hữu trí tuệ đối với các sản phẩm tạo ra từ trí tuệ nhân tạo*, Luận án tiến sĩ Luật học, Trường Đại học Luật Thành phố Hồ Chí Minh, Thành phố Hồ Chí Minh."),
    "phamNgocPha2025": ("vi", "Pha Phạm Ngọc 2025",
        "Phạm Ngọc Pha (2025), “Mô hình khai thác sáng chế hỗ trợ doanh nghiệp nâng cao trình độ và năng lực công nghệ”, *Tạp chí Khoa học và Công nghệ Việt Nam*, (2), 15-18."),
    "nguyenVanPhuc2025": ("vi", "Phúc Nguyễn Văn 2025",
        "Nguyễn Văn Phúc (2025), “Bảo hộ và khai thác quyền sở hữu trí tuệ đối với nhãn hiệu có nguồn gốc từ tri thức truyền thống: Thực tiễn tại tỉnh Thừa Thiên Huế”, *Tạp chí Khoa học Đại học Huế: Khoa học Xã hội và Nhân văn*, 134(6S-1), 111-124."),
    "hoangLanPhuong2019": ("vi", "Phương Hoàng Lan 2019",
        "Hoàng Lan Phương (2019), “Pháp luật về chuyển quyền sử dụng nhãn hiệu: Những bất cập cần khắc phục”, *Tạp chí Khoa học và Công nghệ Việt Nam*, 61(10), 29-33."),
    "phamHongQuat2021": ("vi", "Quất Phạm Hồng 2021",
        "Phạm Hồng Quất, Lương Văn Thường, Nguyễn Minh Ngọc, Lê Ngọc Mỹ (2021), “Khai thác tài sản trí tuệ thúc đẩy phát triển hệ sinh thái khởi nghiệp đổi mới sáng tạo và hệ thống đổi mới sáng tạo ở Việt Nam”, *Tạp chí Chính sách và Quản lý Khoa học và Công nghệ*, 10(4), 60-73."),
    "quocHoi2005": ("vi", "Quốc hội 2005",
        "Quốc hội (2005), *Luật Sở hữu trí tuệ số 50/2005/QH11*, được sửa đổi, bổ sung năm 2009, 2019, 2022 và 2025."),
    "quocHoi2025d": ("vi", "Quốc hội 2025 06 14",
        "Quốc hội (2025), *Luật Công nghiệp công nghệ số số 71/2025/QH15 ngày 14/6/2025*."),
    "quocHoi2025a": ("vi", "Quốc hội 2025 06 27",
        "Quốc hội (2025), *Luật Khoa học, công nghệ và đổi mới sáng tạo số 93/2025/QH15 ngày 27/6/2025*."),
    "quocHoi2025b": ("vi", "Quốc hội 2025 12 10",
        "Quốc hội (2025), *Luật sửa đổi, bổ sung một số điều của Luật Sở hữu trí tuệ số 131/2025/QH15 ngày 10/12/2025*."),
    "quocHoi2025c": ("vi", "Quốc hội 2025 12 11",
        "Quốc hội (2025), *Luật Chuyển đổi số số 148/2025/QH15 ngày 11/12/2025*."),
    "hoThucTai2019": ("vi", "Tài Hồ Thức 2019",
        "Hồ Thức Tài (2019), “Chính sách phát triển nền kinh tế số ở Việt Nam”, *Tạp chí Công Thương*, (13), 36-41."),
    "leThanhTam2025": ("vi", "Tâm Lê Thị Thanh 2025",
        "Lê Thị Thanh Tâm, Hoàng Thị Hải Yến (2025), “Thương mại hóa sáng chế thông qua hoạt động chuyển giao công nghệ theo pháp luật Việt Nam”, *Tạp chí Khoa học Đại học Huế: Khoa học Xã hội và Nhân văn*, 134(6D), 35-46."),
    "nguyenQuocThinh2020": ("vi", "Thịnh Nguyễn Quốc 2020",
        "Nguyễn Quốc Thịnh, Khúc Đại Long, Nguyễn Thu Hương (2020), “Quản trị tài sản trí tuệ trong doanh nghiệp Việt Nam: Động lực cho sự khác biệt hóa”, *Tạp chí Khoa học Thương mại*, (143), 38-44."),
    "ttg2019": ("vi", "Thủ tướng Chính phủ 2019",
        "Thủ tướng Chính phủ (2019), *Quyết định số 1068/QĐ-TTg ngày 22/8/2019 phê duyệt Chiến lược sở hữu trí tuệ đến năm 2030*, Hà Nội."),
    "ttg2022": ("vi", "Thủ tướng Chính phủ 2022",
        "Thủ tướng Chính phủ (2022), *Quyết định số 411/QĐ-TTg ngày 31/3/2022 phê duyệt Chiến lược quốc gia phát triển kinh tế số và xã hội số đến năm 2025, định hướng đến năm 2030*, Hà Nội."),
    "ttg2026": ("vi", "Thủ tướng Chính phủ 2026",
        "Thủ tướng Chính phủ (2026), *Quyết định số 1624/QĐ-TTg ngày 21/8/2026 sửa đổi, bổ sung một số điều của Quyết định số 1068/QĐ-TTg ngày 22/8/2019 phê duyệt Chiến lược sở hữu trí tuệ đến năm 2030*, Hà Nội."),
    "leBichThuy2021": ("vi", "Thủy Lê Thị Bích 2021",
        "Lê Thị Bích Thủy (2021), *Bảo hộ quyền sở hữu trí tuệ đối với sáng chế liên quan đến dược phẩm tại Việt Nam trong điều kiện hội nhập kinh tế quốc tế*, Luận án tiến sĩ Luật học, Trường Đại học Luật Hà Nội, Hà Nội."),
    "hoangVanThuy2024": ("vi", "Thùy Hoàng Văn 2024",
        "Hoàng Văn Thùy (2024), “Bảo vệ quyền sở hữu trí tuệ trong kinh tế số”, *Tạp chí Nghề Luật*, (1), 21-25."),
    "nguyenMinhHuyenTrang2025": ("vi", "Trang Nguyễn Minh Huyền 2025",
        "Nguyễn Minh Huyền Trang (2025), “Quản trị tài sản trí tuệ tại các cơ sở giáo dục đại học: Cơ hội và thách thức trong bối cảnh cuộc Cách mạng công nghiệp 4.0”, *Tạp chí Khoa học Trường Đại học Sư phạm Thành phố Hồ Chí Minh*, 22(1), 123-131."),
    "nguyenThanhTung2026": ("vi", "Tùng Nguyễn Thanh 2026",
        "Nguyễn Thanh Tùng (2026), “Một số hạn chế, bất cập của pháp luật Việt Nam về hợp đồng chuyển giao quyền sử dụng nhãn hiệu và giải pháp hoàn thiện”, *Tạp chí Khoa học Đại học Huế: Khoa học Xã hội và Nhân văn*, 135(6A), 23-34."),
    "nguyenToUyen2023": ("vi", "Uyên Nguyễn Thị Tố 2023",
        "Nguyễn Thị Tố Uyên, Nguyễn Hữu Việt (2023), “Một số vấn đề về thực hiện chính sách phát triển tài sản trí tuệ của Nhà nước tại địa phương”, *Tạp chí Nghiên cứu khoa học và Phát triển*, 2(4), 56-65."),
    "nguyenHuuXuyen2018": ("vi", "Xuyên Nguyễn Hữu 2018",
        "Nguyễn Hữu Xuyên (2018), “Những nút thắt trong khai thác, thương mại hóa sáng chế”, *Tạp chí Khoa học và Công nghệ Việt Nam*, (9), 23-25."),

    # ============================ TIẾNG ANH ============================
    "acemoglu2012": ("en", "Acemoglu 2012",
        "Acemoglu D., Akcigit U. (2012), “Intellectual property rights policy, competition and innovation”, *Journal of the European Economic Association*, 10(1), 1-42."),
    "arora2001book": ("en", "Arora 2001 a",
        "Arora A., Fosfuri A., Gambardella A. (2001), *Markets for Technology: The Economics of Innovation and Corporate Strategy*, MIT Press, Cambridge, MA."),
    "hair2014": ("en", "Hair 2014",
        "Hair J.F., Black W.C., Babin B.J., Anderson R.E. (2014), *Multivariate Data Analysis* (7th ed.), Pearson Education, Harlow."),
    "arora2001": ("en", "Arora 2001 b",
        "Arora A., Fosfuri A., Gambardella A. (2001), “Markets for technology and their implications for corporate strategy”, *Industrial and Corporate Change*, 10(2), 419-451."),
    "arrow1962": ("en", "Arrow 1962",
        "Arrow K.J. (1962), “Economic welfare and the allocation of resources for invention”, in National Bureau of Economic Research, *The Rate and Direction of Inventive Activity: Economic and Social Factors*, Princeton University Press, Princeton, 609-626."),
    "branstetter2006": ("en", "Branstetter 2006",
        "Branstetter L.G., Fisman R., Foley C.F. (2006), “Do stronger intellectual property rights increase international technology transfer? Empirical evidence from U.S. firm-level panel data”, *The Quarterly Journal of Economics*, 121(1), 321-349."),
    "brynjolfsson1993": ("en", "Brynjolfsson 1993",
        "Brynjolfsson E. (1993), “The productivity paradox of information technology”, *Communications of the ACM*, 36(12), 66-77."),
    "buiXuanChung2025": ("en", "Bui Xuan Chung 2025",
        "Bui Xuan Chung (2025), “Measuring the digital economy: International experience and practices in Vietnam”, *TNU Journal of Science and Technology*, 230(15), 105-112."),
    "bukht2017": ("en", "Bukht 2017",
        "Bukht R., Heeks R. (2017), *Defining, Conceptualising and Measuring the Digital Economy*, Development Informatics Working Paper No. 68, Centre for Development Informatics, University of Manchester, Manchester."),
    "chesbrough2003": ("en", "Chesbrough 2003",
        "Chesbrough H.W. (2003), *Open Innovation: The New Imperative for Creating and Profiting from Technology*, Harvard Business School Press, Boston."),
    "dangThanhDat2026": ("en", "Dang Thanh Dat 2026",
        "Dang Thanh Dat (2026), “Policies for the commercialization of university research: International experiences and implications for Vietnam”, *VNU Journal of Science: Policy and Management Studies*, 42(2), 54-75."),
    "dangVietDuc2022": ("en", "Dang Thi Viet Duc 2022",
        "Dang Thi Viet Duc (2022), “Digital economy model in Vietnam”, *VNU Journal of Science: Policy and Management Studies*, 38(2), 88-99."),
    "demsetz1967": ("en", "Demsetz 1967",
        "Demsetz H. (1967), “Toward a theory of property rights”, *The American Economic Review*, 57(2), 347-359."),
    "dunleavy2006": ("en", "Dunleavy 2006",
        "Dunleavy P., Margetts H., Bastow S., Tinkler J. (2006), “New public management is dead: Long live digital-era governance”, *Journal of Public Administration Research and Theory*, 16(3), 467-494."),
    "epo2021": ("en", "European Patent Office 2021",
        "European Patent Office, European Union Intellectual Property Office (2021), *Intellectual Property Rights and Firm Performance in the European Union: Firm-Level Analysis Report*, EUIPO, Alicante."),
    "fasi2022": ("en", "Fasi 2022",
        "Fasi M.A. (2022), “An overview on patenting trends and technology commercialization practices in the university Technology Transfer Offices in USA and China”, *World Patent Information*, 68, 102097."),
    "fink2005": ("en", "Fink 2005",
        "Fink C., Maskus K.E. (eds.) (2005), *Intellectual Property and Development: Lessons from Recent Economic Research*, World Bank and Oxford University Press, Washington, DC."),
    "fisher2001": ("en", "Fisher 2001",
        "Fisher W.W. (2001), “Theories of intellectual property”, in S.R. Munzer (ed.), *New Essays in the Legal and Political Theory of Property*, Cambridge University Press, Cambridge, 168-199."),
    "foster2024": ("en", "Foster 2024",
        "Foster C. (2024), “Intellectual property rights and control in the digital economy: Examining the expansion of M-Pesa”, *The Information Society*, 40(1), 1-17."),
    "gans2008": ("en", "Gans 2008",
        "Gans J.S., Hsu D.H., Stern S. (2008), “The impact of uncertain intellectual property rights on the market for ideas: Evidence from patent grant delays”, *Management Science*, 54(5), 982-997."),
    "gans2003": ("en", "Gans 2003",
        "Gans J.S., Stern S. (2003), “The product market and the market for ‘ideas’: Commercialization strategies for technology entrepreneurs”, *Research Policy*, 32(2), 333-350."),
    "goldfarb2019": ("en", "Goldfarb 2019",
        "Goldfarb A., Tucker C. (2019), “Digital economics”, *Journal of Economic Literature*, 57(1), 3-43."),
    "gould1996": ("en", "Gould 1996",
        "Gould D.M., Gruben W.C. (1996), “The role of intellectual property rights in economic growth”, *Journal of Development Economics*, 48(2), 323-350."),
    "haskel2018": ("en", "Haskel 2018",
        "Haskel J., Westlake S. (2018), *Capitalism without Capital: The Rise of the Intangible Economy*, Princeton University Press, Princeton."),
    "helpman1993": ("en", "Helpman 1993",
        "Helpman E. (1993), “Innovation, imitation, and intellectual property rights”, *Econometrica*, 61(6), 1247-1280."),
    "hochberg2018": ("en", "Hochberg 2018",
        "Hochberg Y.V., Serrano C.J., Ziedonis R.H. (2018), “Patent collateral, investor commitment, and the market for venture lending”, *Journal of Financial Economics*, 130(1), 74-94."),
    "hood1991": ("en", "Hood 1991",
        "Hood C. (1991), “A public management for all seasons?”, *Public Administration*, 69(1), 3-19."),
    "hughes1988": ("en", "Hughes 1988",
        "Hughes J. (1988), “The philosophy of intellectual property”, *Georgetown Law Journal*, 77(2), 287-366."),
    "imf2018": ("en", "International Monetary Fund 2018",
        "International Monetary Fund (2018), *Measuring the Digital Economy*, IMF Policy Paper, IMF, Washington, DC."),
    "leHa2022": ("en", "Le Ha 2022",
        "Le H.T.T., Luong T.T.D. (2022), “Intellectual property management: Case studies of Vietnamese SMEs”, *International Journal of Business Strategy and Social Sciences*, 5(2), 70-87."),
    "leThuHa2022": ("en", "Le Thi Thu Ha 2022",
        "Le Thi Thu Ha, Nguyen Nhu Ngoc, Luong Thi Dai Trang (2022), “The relation between intellectual property management and firm performance of Vietnamese firms in the information and communication technology industry (ICT)”, *VNU Journal of Science: Policy and Management Studies*, 38(1), 87-104."),
    "longTranViet2023": ("en", "Long Tran Viet 2023",
        "Long Tran Viet, Hai Phan Thanh (2023), “Mediating impact of the protection and exploitation of intellectual property rights of local intellectual property on tourism development: An empirical study in Central Vietnam”, *Problems and Perspectives in Management*, 21(2), 767-780."),
    "lundvall1992": ("en", "Lundvall 1992",
        "Lundvall B.-Å. (ed.) (1992), *National Systems of Innovation: Towards a Theory of Innovation and Interactive Learning*, Pinter, London."),
    "luuHoangLong2025a": ("en", "Luu Hoang Long 2025a",
        "Luu Hoang Long (2025a), “Establishing technology park to support the commercialization of intellectual property in higher education institutions”, *VNU Journal of Science: Policy and Management Studies*, 41(2), 43-53."),
    "luuHoangLong2025b": ("en", "Luu Hoang Long 2025b",
        "Luu Hoang Long (2025b), “Building an innovation ecosystem to support the commercialization of intellectual property at Vietnam National University, Hanoi”, *VNU Journal of Science: Policy and Management Studies*, 41(4), 63-73."),
    "mann2018": ("en", "Mann 2018",
        "Mann W. (2018), “Creditor rights and innovation: Evidence from patent collateral”, *Journal of Financial Economics*, 130(1), 25-47."),
    "mansfield1994": ("en", "Mansfield 1994",
        "Mansfield E. (1994), *Intellectual Property Protection, Foreign Direct Investment, and Technology Transfer*, IFC Discussion Paper No. 19, International Finance Corporation, Washington, DC."),
    "maskus2000": ("en", "Maskus 2000",
        "Maskus K.E. (2000), *Intellectual Property Rights in the Global Economy*, Institute for International Economics, Washington, DC."),
    "mazzucato2013": ("en", "Mazzucato 2013",
        "Mazzucato M. (2013), *The Entrepreneurial State: Debunking Public vs. Private Sector Myths*, Anthem Press, London."),
    "merges2011": ("en", "Merges 2011",
        "Merges R.P. (2011), *Justifying Intellectual Property*, Harvard University Press, Cambridge, MA."),
    "mowery2001": ("en", "Mowery 2001",
        "Mowery D.C., Nelson R.R., Sampat B.N., Ziedonis A.A. (2001), “The growth of patenting and licensing by U.S. universities: An assessment of the effects of the Bayh-Dole Act of 1980”, *Research Policy*, 30(1), 99-119."),
    "negroponte1995": ("en", "Negroponte 1995",
        "Negroponte N. (1995), *Being Digital*, Alfred A. Knopf, New York."),
    "nelson1993": ("en", "Nelson 1993",
        "Nelson R.R. (ed.) (1993), *National Innovation Systems: A Comparative Analysis*, Oxford University Press, New York."),
    "neves2021": ("en", "Neves 2021",
        "Neves P.C., Afonso O., Silva D., Sochirca E. (2021), “The link between intellectual property rights, innovation, and growth: A meta-analysis”, *Economic Modelling*, 97, 196-209."),
    "nguyenHuuXuyen2024": ("en", "Nguyen Huu Xuyen 2024",
        "Nguyen Huu Xuyen (2024), “Intellectual property management to serve the innovation activities of Vietnam's enterprise”, *European Science Review*, (5-6), 18-23."),
    "vinhHungNguyen2024": ("en", "Nguyen Vinh Hung 2024",
        "Nguyen V.H., Nguyen D.A. (2024), “Managing the digital economy: The case of Vietnam”, *Forum for Economic and Financial Studies*, 2(4), 2132."),
    "north1990": ("en", "North 1990",
        "North D.C. (1990), *Institutions, Institutional Change and Economic Performance*, Cambridge University Press, Cambridge."),
    "oecd2014": ("en", "OECD 2014",
        "OECD, World Bank (2014), *Science, Technology and Innovation in Viet Nam*, OECD Reviews of Innovation Policy, OECD Publishing, Paris."),
    "oecd2020": ("en", "OECD 2020",
        "OECD (2020), *A Roadmap toward a Common Framework for Measuring the Digital Economy*, Report for the G20 Digital Economy Task Force, OECD, Paris."),
    "pan2022": ("en", "Pan 2022",
        "Pan W., Xie T., Wang Z., Ma L. (2022), “Digital economy: An innovation driver for total factor productivity”, *Journal of Business Research*, 139, 303-311."),
    "park2008": ("en", "Park 2008",
        "Park W.G. (2008), “International patent protection: 1960-2005”, *Research Policy*, 37(4), 761-766."),
    "shapiro1999": ("en", "Shapiro 1999",
        "Shapiro C., Varian H.R. (1999), *Information Rules: A Strategic Guide to the Network Economy*, Harvard Business School Press, Boston."),
    "siegel2003": ("en", "Siegel 2003",
        "Siegel D.S., Waldman D., Link A. (2003), “Assessing the impact of organizational practices on the relative productivity of university technology transfer offices: An exploratory study”, *Research Policy*, 32(1), 27-48."),
    "sinnreich2019": ("en", "Sinnreich 2019",
        "Sinnreich A. (2019), *The Essential Guide to Intellectual Property*, Yale University Press, New Haven."),
    "tapscott1996": ("en", "Tapscott 1996",
        "Tapscott D. (1996), *The Digital Economy: Promise and Peril in the Age of Networked Intelligence*, McGraw-Hill, New York."),
    "teece1986": ("en", "Teece 1986",
        "Teece D.J. (1986), “Profiting from technological innovation: Implications for integration, collaboration, licensing and public policy”, *Research Policy*, 15(6), 285-305."),
    "thompson1996": ("en", "Thompson 1996",
        "Thompson M.A., Rushing F.W. (1996), “An empirical analysis of the impact of patent protection on economic growth”, *Journal of Economic Development*, 21(2), 61-79."),
    "tranVanHai2022": ("en", "Tran Van Hai 2022",
        "Tran Van Hai (2022), “Applying digital competence framework in exploiting information for commercialisation of intellectual property rights purposes”, *VNU Journal of Science: Policy and Management Studies*, 38(3), 41-50."),
    "unctad2019": ("en", "UNCTAD 2019",
        "UNCTAD (2019), *Digital Economy Report 2019: Value Creation and Capture: Implications for Developing Countries*, United Nations, New York and Geneva."),
    "williams2013": ("en", "Williams 2013",
        "Williams H.L. (2013), “Intellectual property rights and innovation: Evidence from the human genome”, *Journal of Political Economy*, 121(1), 1-27."),
    "wipo2024": ("en", "World Intellectual Property Organization 2024",
        "World Intellectual Property Organization (2024), *World Intellectual Property Report 2024: Making Innovation Policy Work for Development*, WIPO, Geneva."),
    "wipo2026": ("en", "World Intellectual Property Organization 2026",
        "World Intellectual Property Organization (2026), *World Intellectual Property Report 2026: Technology on the Move*, WIPO, Geneva."),
    "yang2001": ("en", "Yang 2001",
        "Yang G., Maskus K.E. (2001), “Intellectual property rights and licensing: An econometric investigation”, *Weltwirtschaftliches Archiv*, 137(1), 58-79."),
    # ------------------------------ bổ sung ngày 30/9/2026 (đã đối chiếu bản gốc trong 01_NotebookLM_Inputs)
    "phamMinhHuyen2024": ("vi", "Huyền Phạm Minh 2024",
        "Phạm Minh Huyền (2024), *Giới hạn quyền tác giả, quyền liên quan - Những vấn đề lý luận và thực tiễn*, Luận án tiến sĩ Luật học, Trường Đại học Luật Hà Nội, Hà Nội."),
    "tranVanHai2021": ("vi", "Hải Trần Văn 2021",
        "Trần Văn Hải (2021), *Chính sách pháp luật hình sự Việt Nam đối với các tội xâm phạm quyền sở hữu trí tuệ*, Luận án tiến sĩ Luật học, Học viện Khoa học xã hội, Hà Nội."),
    "huaThiHong2023": ("vi", "Hồng Hứa Thị 2023",
        "Hứa Thị Hồng (2023), *Bảo vệ quyền sở hữu trí tuệ tại biên giới thông qua kiểm soát hàng hoá giả mạo về sở hữu trí tuệ của Hải quan Việt Nam*, Luận án tiến sĩ Luật học, Trường Đại học Luật Hà Nội, Hà Nội."),
    "tranThiLan2025": ("vi", "Lan Trần Thị 2025",
        "Trần Thị Lan (2025), *Các yếu tố ảnh hưởng đến phát triển kinh tế số ở Việt Nam*, Luận án tiến sĩ Kinh tế, Học viện Khoa học xã hội, Hà Nội."),
    "nguyenPhuongThao2024": ("vi", "Thảo Nguyễn Phương 2024",
        "Nguyễn Phương Thảo (2024), “Phương pháp đo lường kinh tế số của các tổ chức trên thế giới và đề xuất cho Việt Nam”, *Tạp chí Kinh tế và Dự báo*, (21), 27-30."),
    "nguyenThiHaiHa2023": ("vi", "Hà Nguyễn Thị Hải 2023",
        "Nguyễn Thị Hải Hà (2023), “Đánh giá hiệu quả quản lý nhà nước trong nền kinh tế số”, *Tạp chí Phát triển bền vững Vùng*, 13(2), 11-20."),
    "ngoHoaiSon2022": ("vi", "Sơn Ngô Hoài 2022",
        "Ngô Hoài Sơn, Nguyễn Lê Kim Kiều (2022), “Vận dụng lý thuyết phương pháp quản lý nhà nước về kinh tế để xây dựng nền kinh tế số ở Việt Nam”, *Tạp chí Công Thương*, (21), 248-254."),
    "nguyenThiTuyetNga2025": ("vi", "Nga Nguyễn Thị Tuyết 2025",
        "Nguyễn Thị Tuyết Nga (2025), “Hoàn thiện chính sách sở hữu trí tuệ trong nền kinh tế số ở Việt Nam hiện nay”, *Tạp chí Quản lý nhà nước* (điện tử), đăng ngày 30/6/2025, quanlynhanuoc.vn."),
    "truongNamTrung2020": ("en", "Truong Nam Trung 2020",
        "Truong Nam Trung (2020), “Institutional improvements for the development of digital economy in Vietnam”, *Tạp chí Công Thương*, (25), 99-104."),
    "oecd2014dm": ("en", "OECD 2014 Measuring",
        "OECD (2014), *Measuring the Digital Economy: A New Perspective*, OECD Publishing, Paris."),
    "barefoot2018": ("en", "Barefoot 2018",
        "Barefoot K., Curtis D., Jolliff W., Nicholson J.R., Omohundro R. (2018), *Defining and Measuring the Digital Economy*, Working Paper, Bureau of Economic Analysis, U.S. Department of Commerce."),
    "wipo2024b": ("en", "World Intellectual Property Organization 2024b",
        "World Intellectual Property Organization, Luiss Business School (2024), *World Intangible Investment Highlights*, WIPO, Geneva."),
    "unctad2017": ("en", "UNCTAD 2017",
        "UNCTAD (2017), *The 'New' Digital Economy and Development*, UNCTAD Technical Notes on ICT for Development No. 8, UNCTAD."),
    "dahlman2016": ("en", "Dahlman 2016",
        "Dahlman C., Mealy S., Wermelinger M. (2016), *Harnessing the digital economy for developing countries*, OECD Development Centre Working Papers No. 334, OECD Publishing, Paris."),
    "chen2022": ("en", "Chen 2022",
        "Chen W., Wu Y. (2022), “Does intellectual property protection stimulate digital economy development?”, *Journal of Applied Economics*, 25(1), 723-730."),
    "zheng2023": ("en", "Zheng 2023",
        "Zheng P., Li Z., Zhuang Z. (2023), “The impact of judicial protection of intellectual property on digital innovation: Evidence from China”, *Finance Research Letters*, 58, 104257."),
    "yuan2025": ("en", "Yuan 2025",
        "Yuan B., Li W. (2025), “Legal infrastructures for firm innovation: Effects of intellectual property protection in the era of digital economy”, *Finance Research Letters*, 71, 106343."),
    "ding2025": ("en", "Ding 2025",
        "Ding T., Yang L. (2025), “Intellectual property protection and corporate digital transformation: An empirical analysis from the perspectives of intellectual property protection and digital governance”, *International Review of Economics & Finance*, 100, 104125."),
}
